# docker-compose.yml

version: '3.9'    
services:
  mp_spdz:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        HOST_DATA_SRC: mpSPDZ_SRC_v0.4.0.zip
        SRC_ZIP_FOLDER: MP-SPDZ-0.4.0
        b4M_PATCH_BaseMachine_CPP: patch-for-b4M/BaseMachine_0.4.cpp
        b4M_PATCH_BaseMachine_H: patch-for-b4M/BaseMachine_0.4.h
        BaseMachine_CPP_TARGET: Processor/BaseMachine.cpp
        BaseMachine_H_TARGET: Processor/BaseMachine.h
        # - HOST_DATA_FILE_NETWORK_SETUP_LAN="setup-network_LAN.sh"
        # - HOST_DATA_FILE_NETWORK_SETUP_WAN="setup-network_WAN.sh"
        ## Within WORK_DIR
        HOST_SHARE_DIR_LOGS: Dock-Point/Logs
        HOST_SHARE_DIR_DATA: Dock-Point/Data
    image: mp_spdz_v0_4_0_from_2024_nov_ubuntu_all_protos
    # image: mp_spdz_v0_4_0_x_2025_apr_29_ubuntu_all_protos

